"""
CardioEQ AI — Explainable Insight Generator
==============================================
Every insight surfaced on the dashboard follows the same four-part
explainable structure the platform spec calls for:

    pattern        -> what was detected
    why_detected   -> the quantitative trigger condition
    impact         -> what it means for cardiovascular health
    recommendation -> a concrete, personalized next step

These are rule-based (thresholds derived from the REFERENCE_RANGES in
scoring.py and from within-subject trend analysis), not generated by an
LLM — this keeps them deterministic, auditable, and reproducible, which
matters for a "research-grade, explainable" health platform. The AI
assistant (see backend/app/services/assistant.py) is the layer that
translates these structured insights into conversational language.
"""

import numpy as np
import pandas as pd


def _trend_slope(series: pd.Series) -> float:
    if len(series) < 3:
        return 0.0
    y = series.dropna().to_numpy()
    if len(y) < 3:
        return 0.0
    x = np.arange(len(y))
    return float(np.polyfit(x, y, 1)[0])


def generate_session_insights(session_windows: pd.DataFrame, subject_meta: dict) -> list[dict]:
    """session_windows: all windows for one subject+activity, ordered by window_index."""
    insights = []
    sw = session_windows.sort_values("window_index")

    # 1. HRV depression
    rmssd_mean = sw["rmssd"].mean()
    if pd.notna(rmssd_mean) and rmssd_mean < 20:
        insights.append({
            "pattern": "Low Heart Rate Variability (RMSSD)",
            "why_detected": f"Average RMSSD across this session was {rmssd_mean:.1f}ms, "
                             f"below the 20ms threshold associated with reduced parasympathetic activity.",
            "impact": "Lower RMSSD reflects reduced vagal (parasympathetic) regulation of the heart, "
                      "which over time is associated with poorer stress resilience and higher cardiovascular load.",
            "recommendation": "Consider paced breathing exercises (e.g. 6 breaths/min) and prioritizing sleep "
                               "consistency, both of which are reliably shown to raise RMSSD.",
            "severity": "moderate" if rmssd_mean > 12 else "high",
        })

    # 2. Elevated resting heart rate for the 'sit' baseline activity
    if subject_meta.get("activity") == "sit":
        hr_mean = sw["heart_rate"].mean()
        if pd.notna(hr_mean) and hr_mean > 100:
            insights.append({
                "pattern": "Elevated Resting Heart Rate",
                "why_detected": f"Mean heart rate during the seated baseline session was {hr_mean:.0f} bpm, "
                                 f"above the 100 bpm resting threshold.",
                "impact": "A persistently elevated resting heart rate is an independent marker of "
                          "cardiovascular strain and reduced cardiorespiratory fitness.",
                "recommendation": "Recommend a clinical follow-up to rule out underlying causes (anemia, "
                                   "thyroid, dehydration) and consider a structured aerobic conditioning plan.",
                "severity": "high" if hr_mean > 110 else "moderate",
            })

    # 3. Stress index trending upward across the session
    slope = _trend_slope(sw["stress_index"])
    if slope > 0.8:
        insights.append({
            "pattern": "Rising Stress Trajectory",
            "why_detected": f"Stress index (derived from skin conductance) increased by "
                             f"~{slope:.1f} points per 30s window across the session, with no plateau.",
            "impact": "Sustained, unresolving sympathetic activation prevents recovery and is linked to "
                      "elevated blood pressure and arrhythmia risk over repeated exposure.",
            "recommendation": "Insert active recovery breaks during sustained cognitive or physical load, "
                               "and monitor whether this pattern repeats across sessions.",
            "severity": "moderate",
        })

    # 4. Good recovery behavior (positive insight, not just risk flags)
    recovery_mean = sw["recovery_rate"].mean()
    if pd.notna(recovery_mean) and recovery_mean > 1.5:
        insights.append({
            "pattern": "Strong Post-Exertion Recovery",
            "why_detected": f"Heart rate declined at ~{recovery_mean:.1f} bpm per window on average, "
                             f"indicating efficient autonomic recovery within the session.",
            "impact": "Fast heart-rate recovery is one of the strongest fitness-linked predictors of "
                      "lower long-term cardiovascular risk.",
            "recommendation": "This is a positive marker — maintain current activity and recovery habits.",
            "severity": "positive",
        })

    # 5. SpO2 dip
    spo2_min = sw["spo2"].min()
    if pd.notna(spo2_min) and spo2_min < 93:
        insights.append({
            "pattern": "Transient Oxygen Saturation Dip",
            "why_detected": f"Minimum SpO2 recorded was {spo2_min:.0f}%, below the 93% threshold.",
            "impact": "Even transient desaturation, if recurrent, can place additional load on the "
                      "cardiopulmonary system.",
            "recommendation": "If this recurs across multiple sessions, recommend pulse-oximetry follow-up "
                               "and screening for sleep-disordered breathing.",
            "severity": "moderate",
        })

    if not insights:
        insights.append({
            "pattern": "Stable Physiological Profile",
            "why_detected": "No biomarker in this session crossed an explainable risk threshold.",
            "impact": "Cardiovascular indicators during this session were within expected healthy ranges.",
            "recommendation": "Continue current monitoring cadence; no action needed.",
            "severity": "positive",
        })

    return insights
